### ISSUE TITLE
日本語翻訳 Tracking Issue

### ISSUE THREAD

**Issue by t-hamano** [jawordpressorg/theme-handbook#21]
このissueは、テーマハンドブックの日本語化にあたり、原文の対象ページをリストアップし、各ページの進捗を管理するものです。

- [ ] [Index](https://developer.wordpress.org/themes/)
  - #5
  - #3
- [ ] [Getting Started](https://developer.wordpress.org/themes/getting-started)
- [ ] [Getting Started > Who Should Read This Handbook?](https://developer.wordpress.org/themes/getting-started/who-should-read-this-handbook)
- [x] [Getting Started > What is a Theme?](https://developer.wordpress.org/themes/getting-started/what-is-a-theme) #7
- [ ] [Getting Started > WordPress Licensing & the GPL](https://developer.wordpress.org/themes/getting-started/wordpress-licensing-the-gpl)
- [ ] [Getting Started > Setting up a Development Environment](https://developer.wordpress.org/themes/getting-started/setting-up-a-development-environment)
- [ ] [Getting Started > Theme Development Examples](https://developer.wordpress.org/themes/getting-started/theme-development-examples)
- [ ] [Theme Basics](https://developer.wordpress.org/themes/basics)
- [ ] [Theme Basics > Theme Functions](https://developer.wordpress.org/themes/basics/theme-functions)
- [ ] [Theme Basics > Template Files](https://developer.wordpress.org/themes/basics/template-files)
- [ ] [Theme Basics > Main Stylesheet (style.css)](https://developer.wordpress.org/themes/basics/main-stylesheet-style-css)
- [x] [Theme Basics > Post Types](https://developer.wordpress.org/themes/basics/post-types) #20
- [ ] [Theme Basics > Organizing Theme Files](https://developer.wordpress.org/themes/basics/organizing-theme-files)
- [x] [Theme Basics > Template Hierarchy](https://developer.wordpress.org/themes/basics/template-hierarchy)
  - #2
  - #11
- [ ] [Theme Basics > Including CSS & JavaScript](https://developer.wordpress.org/themes/basics/including-css-javascript)
- [ ] [Theme Basics > Categories, Tags, & Custom Taxonomies](https://developer.wordpress.org/themes/basics/categories-tags-custom-taxonomies)
- [ ] [Theme Basics > Tools & Resources](https://developer.wordpress.org/themes/basics/tools-resources)
- [ ] [Block themes](https://developer.wordpress.org/themes/block-themes)
- [ ] [Block themes > Block theme setup](https://developer.wordpress.org/themes/block-themes/block-theme-setup)
- [ ] [Block themes > Templates and template parts](https://developer.wordpress.org/themes/block-themes/templates-and-template-parts)
- [ ] [Block themes > Theme.json](https://developer.wordpress.org/themes/advanced-topics/theme-json)
- [ ] [Block themes > Converting a classic theme to a block theme](https://developer.wordpress.org/themes/block-themes/converting-a-classic-theme-to-a-block-theme)
- [ ] [Block themes > Converting a classic theme to a block theme > Converting customizer settings to block patterns](https://developer.wordpress.org/themes/block-themes/converting-customizer-settings-to-block-patterns)
- [ ] [Block themes > Creating new themes using the Site Editor](https://developer.wordpress.org/themes/block-themes/creating-new-themes-using-the-site-editor)
- [ ] [Block themes > Internationalization](https://developer.wordpress.org/themes/block-themes/internationalization)
- [ ] [Classic themes](https://developer.wordpress.org/themes/classic-themes)
- [ ] [Classic themes > Your First Theme](https://developer.wordpress.org/themes/getting-started/your-first-theme)
- [ ] [Classic themes > Linking Theme Files & Directories](https://developer.wordpress.org/themes/basics/linking-theme-files-directories)
- [x] [Classic themes > The Loop](https://developer.wordpress.org/themes/basics/the-loop) #20
- [ ] [Classic themes > Template Files Section](https://developer.wordpress.org/themes/template-files-section)
- [ ] [Classic themes > Template Files Section > Post Templates](https://developer.wordpress.org/themes/template-files-section/post-template-files)
- [ ] [Classic themes > Template Files Section > Page Templates](https://developer.wordpress.org/themes/template-files-section/page-template-files)
- [ ] [Classic themes > Template Files Section > Attachment Template Files](https://developer.wordpress.org/themes/template-files-section/attachment-template-files)
- [ ] [Classic themes > Template Files Section > Custom Post Type Template Files](https://developer.wordpress.org/themes/template-files-section/custom-post-type-template-files)
- [ ] [Classic themes > Template Files Section > Partial and Miscellaneous Template Files](https://developer.wordpress.org/themes/template-files-section/partial-and-miscellaneous-template-files)
- [ ] [Classic themes > Template Files Section > Partial and Miscellaneous Template Files > Comment Template](https://developer.wordpress.org/themes/template-files-section/partial-and-miscellaneous-template-files/comment-template)
- [ ] [Classic themes > Template Files Section > Taxonomy Templates](https://developer.wordpress.org/themes/template-files-section/taxonomy-templates)
- [ ] [Classic themes > Template Files Section > 404 Pages](https://developer.wordpress.org/themes/functionality/404-pages)
- [ ] [Classic themes > Conditional Tags](https://developer.wordpress.org/themes/basics/conditional-tags)
- [x] [Classic themes > Template Tags](https://developer.wordpress.org/themes/basics/template-tags) #20
- [ ] [Classic themes > Theme Functionality](https://developer.wordpress.org/themes/functionality)
- [ ] [Classic themes > Theme Functionality > Core-Supported Features](https://developer.wordpress.org/themes/functionality/core-supported)
- [ ] [Classic themes > Theme Functionality > Core-Supported Features > Administration Menus](https://developer.wordpress.org/themes/functionality/administration-menus)
- [ ] [Classic themes > Theme Functionality > Core-Supported Features > Custom Headers](https://developer.wordpress.org/themes/functionality/custom-headers)
- [ ] [Classic themes > Theme Functionality > Core-Supported Features > Custom Logo](https://developer.wordpress.org/themes/functionality/custom-logo)
- [ ] [Classic themes > Theme Functionality > Core-Supported Features > Post Formats](https://developer.wordpress.org/themes/functionality/post-formats)
- [ ] [Classic themes > Theme Functionality > Core-Supported Features > Sticky Posts](https://developer.wordpress.org/themes/functionality/sticky-posts)
- [ ] [Classic themes > Theme Functionality > Sidebars](https://developer.wordpress.org/themes/functionality/sidebars)
- [ ] [Classic themes > Theme Functionality > Widgets](https://developer.wordpress.org/themes/functionality/widgets)
- [ ] [Classic themes > Theme Functionality > Navigation Menus](https://developer.wordpress.org/themes/functionality/navigation-menus)
- [ ] [Classic themes > Theme Functionality > Pagination](https://developer.wordpress.org/themes/functionality/pagination)
- [ ] [Classic themes > Theme Functionality > Media](https://developer.wordpress.org/themes/functionality/media)
- [ ] [Classic themes > Theme Functionality > Media > Audio](https://developer.wordpress.org/themes/functionality/media/audio)
- [ ] [Classic themes > Theme Functionality > Media > Images](https://developer.wordpress.org/themes/functionality/media/images)
- [ ] [Classic themes > Theme Functionality > Media > Galleries](https://developer.wordpress.org/themes/functionality/media/galleries)
- [ ] [Classic themes > Theme Functionality > Media > Video](https://developer.wordpress.org/themes/functionality/media/video)
- [ ] [Classic themes > Theme Functionality > Featured Images & Post Thumbnails](https://developer.wordpress.org/themes/functionality/featured-images-post-thumbnails)
- [ ] [Classic themes > Theme Functionality > Internationalization](https://developer.wordpress.org/themes/functionality/internationalization)
- [ ] [Classic themes > Theme Functionality > Localization](https://developer.wordpress.org/themes/functionality/localization)
- [ ] [Classic themes > Theme Functionality > Theme Options – The Customizer API](https://developer.wordpress.org/themes/customize-api)
- [ ] [Classic themes > Theme Functionality > Theme Options – The Customizer API > Customizer Objects](https://developer.wordpress.org/themes/customize-api/customizer-objects)
- [ ] [Classic themes > Theme Functionality > Theme Options – The Customizer API > Tools for Improved User Experience](https://developer.wordpress.org/themes/customize-api/tools-for-improved-user-experience)
- [ ] [Classic themes > Theme Functionality > Theme Options – The Customizer API > The Customizer JavaScript API](https://developer.wordpress.org/themes/customize-api/the-customizer-javascript-api)
- [ ] [Classic themes > Theme Functionality > Theme Options – The Customizer API > JavaScript/Underscore.js-Rendered Custom Controls](https://developer.wordpress.org/themes/customize-api/javascriptunderscore-js-rendered-custom-controls)
- [ ] [Classic themes > Theme Functionality > Theme Options – The Customizer API > Advanced Usage](https://developer.wordpress.org/themes/customize-api/advanced-usage)
- [ ] [Accessibility](https://developer.wordpress.org/themes/functionality/accessibility)
- [ ] [Accessibility > Block theme accessibility](https://developer.wordpress.org/themes/functionality/block-theme-accessibility) #17
- [ ] [Theme Security](https://developer.wordpress.org/themes/theme-security)
- [ ] [Theme Security > Theme security issues](https://developer.wordpress.org/themes/theme-security/theme-security-issues)
- [ ] [Theme Security > Data Sanitization/Escaping](https://developer.wordpress.org/themes/theme-security/data-sanitization-escaping)
- [ ] [Theme Security > Data Validation](https://developer.wordpress.org/themes/theme-security/data-validation)
- [ ] [Theme Security > Using Nonces](https://developer.wordpress.org/themes/theme-security/using-nonces)
- [ ] [Theme Security > Common Vulnerabilities](https://developer.wordpress.org/themes/theme-security/common-vulnerabilities)
- [ ] [Theme Privacy](https://developer.wordpress.org/themes/theme-privacy)
- [ ] [Advanced Theme Topics](https://developer.wordpress.org/themes/advanced-topics)
- [ ] [Advanced Theme Topics > Child Themes](https://developer.wordpress.org/themes/advanced-topics/child-themes)
- [ ] [Advanced Theme Topics > UI Best Practices](https://developer.wordpress.org/themes/advanced-topics/ui-best-practices)
- [ ] [Advanced Theme Topics > JavaScript Best Practices](https://developer.wordpress.org/themes/advanced-topics/javascript-best-practices)
- [ ] [Advanced Theme Topics > Theme Testing](https://developer.wordpress.org/themes/advanced-topics/theme-testing)
- [ ] [Advanced Theme Topics > Validating Your Theme](https://developer.wordpress.org/themes/advanced-topics/validating-your-theme)
- [ ] [Advanced Theme Topics > Plugin API Hooks](https://developer.wordpress.org/themes/advanced-topics/plugin-api-hooks)
- [ ] [Advanced Theme Topics > Block patterns](https://developer.wordpress.org/themes/advanced-topics/block-patterns)
- [ ] [Advanced Theme Topics > Theme.json](https://developer.wordpress.org/themes/advanced-topics/theme-json)
- [ ] [Advanced Theme Topics > Custom block styles](https://developer.wordpress.org/themes/advanced-topics/custom-block-styles)
- [ ] [Releasing Your Theme](https://developer.wordpress.org/themes/releasing-your-theme)
- [ ] [Releasing Your Theme > Required Theme Files](https://developer.wordpress.org/themes/releasing-your-theme/required-theme-files)
- [ ] [Releasing Your Theme > Testing](https://developer.wordpress.org/themes/releasing-your-theme/testing)
- [ ] [Releasing Your Theme > Theme Review Guidelines](https://developer.wordpress.org/themes/releasing-your-theme/theme-review-guidelines)
- [ ] [Releasing Your Theme > Writing Documentation](https://developer.wordpress.org/themes/releasing-your-theme/writing-documentation)
- [ ] [Releasing Your Theme > Submitting Your Theme to WordPress.org](https://developer.wordpress.org/themes/releasing-your-theme/submitting-your-theme-to-wordpress-org)
- [ ] [Releasing Your Theme > Updating Your Theme](https://developer.wordpress.org/themes/releasing-your-theme/updating-your-theme)
- [ ] [References](https://developer.wordpress.org/themes/references)
- [ ] [References > List of Template Tags](https://developer.wordpress.org/themes/references/list-of-template-tags)
- [ ] [References > List of Conditional Tags](https://developer.wordpress.org/themes/references/list-of-conditional-tags)
- [ ] [Credits](https://developer.wordpress.org/themes/credits)
- [ ] [Feedback](https://developer.wordpress.org/themes/credits/feedback)

**Comment by atachibana** [comment]
@t-hamano 
テーマハンドブックはオーバーホールしようとしていますね。少し注意されたほうが良いと思います。
https://github.com/WordPress/Documentation-Issue-Tracker/issues/816

**Comment by t-hamano** [comment]
新しいTracking Issueとして #39 を立てたので、こちらはクローズしたいと思います。
